### PR TITLE
fix(docs): Update header in markdown files

### PR DESCRIPTION
**Pull request by maximiliantechritz**
Hi everyone,

I experienced that the headers in multiple Markdown files were incorrectly implemented. That caused some errors when fetching the docs. I fixed these files with this PR.

### CODE REVIEW

**Comment by maximiliantechritz** [comment]
There are some additional files which needs to be fixed. Further commits will follow.

**Review by Dkaykay — APPROVED** [review]

**Comment by maximiliantechritz** [comment]
I kindly ask for another review to merge this PR. @linouk23 Could you take over please?

**Comment by linouk23** [comment]
Thanks for creating this PR @maximiliantechritz!

Unfortunately our repository isn't setup in a way to accept 3rd party contributions but we will make a similar change internally and include it to our next release, thanks!

**Comment by maximiliantechritz** [comment]
Thanks for the info. Should I then close the PR for now?

**Comment by linouk23** [comment]
Let's keep it open for now and then we could close it once our latest release contains this change.

**Pull request closed without merging**
