### PR TITLE
Allow subjects with name containing slashes

### PR DESCRIPTION
**Pull request by FabioBatSilva**
Should fix : https://github.com/confluentinc/terraform-provider-confluent/issues/236

### CODE REVIEW

**Comment by linouk23** [comment]
Thanks for creating a great PR @FabioBatSilva!

Unfortunately our CI doesn't allow community PRs yet but we'll merge this fix or a slightly updated version of it internally (and include to our next release) and will work on fixing our CI to allow community PRs in the future!

**Comment by maxgr0** [comment]
Hey @linouk23, is there any update on this? 
This bug is at the moment preventing us to finish our migration from MSK to Confluent. 🙁

**Comment by linouk23** [comment]
@maxgr0 we're on it and it should be included in our next release of TF Provider, we'll keep you updated!

**Comment by linouk23** [comment]
@FabioBatSilva @maxgr0 @noahseger we resolved this issue in the latest [release](https://github.com/confluentinc/terraform-provider-confluent/blob/master/CHANGELOG.md#1420-may-9-2023) (1.42.0) of TF Provider for Confluent.

**Pull request closed without merging**
