### PR TITLE
Update confluent_connector.md

### PR DESCRIPTION
**Pull request by fprojetto**
as per docs: https://docs.confluent.io/cloud/current/connectors/cc-kinesis-source.html#aws-credentials

### CODE REVIEW

**Comment by linouk23** [comment]
Thanks for creating a PR! I agree there's this difference with Kinesis source connector but our example seems to represent Amazon S3 Sink [connector](https://docs.confluent.io/cloud/current/connectors/cc-s3-sink.html).

**Comment by linouk23** [comment]
image

**Comment by fprojetto** [comment]
Yes, but I have just run your example and it did not work. 

```Error: error creating Connector "*****": error validating config: 1. "aws.secret.key.id" : ["\"aws.secret.key.id\" is required"]```

**Comment by linouk23** [comment]
Wait, it didn't work for S3 Sink Connector? 😮

**Comment by fprojetto** [comment]
oh sorry. No, just for kinesis. You can close the PR again 😅

**Comment by linouk23** [comment]
Thanks! By the way, will it be helpful if we add examples for more connectors and not just S3 Sink one?

**Pull request closed without merging**
